recipe: default.v1
language: de
pipeline:
- name: SpacyNLP
  model: de_core_news_md
- name: SpacyTokenizer
- name: RegexFeaturizer
  case_sensitive: true
- name: SpacyFeaturizer
- name: LexicalSyntacticFeaturizer
  features:
  - - low
    - title
    - upper
    - suffix2
  - - EOS
    - title
    - suffix5
  - - prefix2
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 2
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.1
  ambiguity_threshold: 0.1
policies:
- name: RulePolicy
  core_fallback_threshold: 0.15
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
